apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: goadmin
  namespace: goadmin
  labels:
    app.kubernetes.io/name: goadmin
    app.kubernetes.io/component: backend
spec:
  ingressClassName: nginx
  rules:
    - host: goadmin.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: goadmin-web
                port:
                  name: http
