apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: goadmin
resources:
  - namespace.yaml
  - configmap.yaml
  - deployment.yaml
  - deployment-web.yaml
  - service.yaml
  - service-web.yaml
  - ingress.yaml
