apiVersion: v1
kind: Secret
metadata:
  name: goadmin-secret
  namespace: goadmin
  labels:
    app.kubernetes.io/name: goadmin
    app.kubernetes.io/component: server
type: Opaque
stringData:
  GOADMIN_DATABASE_DSN: goadmin:goadmin@tcp(mysql.goadmin.svc.cluster.local:3306)/goadmin?charset=utf8mb4&parseTime=True&loc=Local
  GOADMIN_AUTH_JWT_SECRET: change-me-in-production
