replicaCount: 1

image:
  tag: test

frontend:
  replicaCount: 1
  image:
    tag: test

config:
  goadminEnv: test
  appEnv: test
  serverHttpHost: 0.0.0.0
  logLevel: info
  databaseAutoMigrate: true
  tenantEnabled: true

ingress:
  enabled: false
