replicaCount: 2

image:
  tag: prod

frontend:
  replicaCount: 1
  image:
    tag: prod

config:
  goadminEnv: prod
  appEnv: prod
  serverHttpHost: 0.0.0.0
  logLevel: info
  logFormat: json
  databaseAutoMigrate: true
  tenantEnabled: true

ingress:
  enabled: true
  hosts:
    - host: goadmin.example.com
      paths:
        - path: /
          pathType: Prefix
  tls: []
