replicaCount: 1

image:
  tag: dev

frontend:
  replicaCount: 1
  image:
    tag: dev

config:
  goadminEnv: dev
  appEnv: dev
  serverHttpHost: 0.0.0.0
  logLevel: debug
  logFormat: console
  databaseAutoMigrate: true
  databaseLogSql: true
  tenantEnabled: true

ingress:
  enabled: false
