apiVersion: v1
kind: Secret
metadata:
  name: {{ include "goadmin.fullname" . }}-secret
  labels:
    {{- include "goadmin.labels" . | nindent 4 }}
type: Opaque
stringData:
  GOADMIN_DATABASE_DSN: {{ .Values.secret.databaseDsn | quote }}
  GOADMIN_AUTH_JWT_SECRET: {{ .Values.secret.jwtSecret | quote }}
