apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: goadmin
resources:
  - ../../namespace.yaml
  - ../../configmap.yaml
  - ../../deployment.yaml
  - ../../service.yaml
  - ../../ingress.yaml
images:
  - name: ghcr.io/your-org/goadmin
    newTag: prod
patchesStrategicMerge:
  - patch-configmap.yaml
  - patch-deployment.yaml
patchesJson6902:
  - target:
      group: networking.k8s.io
      version: v1
      kind: Ingress
      name: goadmin
    path: patch-ingress.json
